spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.ssl.enabled=true

jwt.secret=${JWT_SECRET}
jwt.access-token.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-token.expiration=${JWT_REFRESH_EXPIRATION}

api.gpt.key=${GPT_KEY}
api.hira.key=${HIRA_KEY}
api.hira.url=${HIRA_URL}
api.deepl.key=${DEEPL_KEY}
api.googleocr.key=${GOOGLE_OCR_KEY}
api.vision.key=${VISION_KEY}
api.firebase.key=file:/app/firebase/healyx-firebase.json

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.cloud.aws.region.static=ap-northeast-2
cloud.aws.s3.bucket=${S3_BUCKET_NAME}

# Grafana 연동용 Prometheus 메트릭 엔드포인트 추가
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=never

# Grafana 메트릭 연동 추가
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=healyx

# Multipart 업로드 크기 설정
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=50MB