spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

api.gpt.key=${GPT_KEY}
api.hira.key=${HIRA_KEY}
api.deepl.key=${DEEPL_KEY}
api.googleocr.key=${GOOGLE_OCR_KEY}

spring.cloud.aws.region.static=ap-northeast-2
cloud.aws.s3.bucket=${S3_BUCKET_NAME}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never